# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Release'
description: 'GitHub Release with assets'
inputs:
  tag:
    description: 'Tag'
    required: false
    default: 'default'
  token:
    description: 'GitHub repo token'
    required: true
  title:
    description: 'GitHub release title'
    required: true
    default: 'Release'
  body:
    description: 'GitHub release body'
    required: false
    default: '*'
outputs:
  query: # id of output
    description: 'debug query'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.token }}
    - ${{ inputs.title }}
    - ${{ inputs.body }}
